// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wktlryapcfkmrspwfyvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdGxyeWFwY2ZrbXJzcHdmeXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjc5MjksImV4cCI6MjA2NjYwMzkyOX0.rlHiMC_cNT-a8BUZsFpbXswusKQKwLqpUrWcentop3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);